export const arrayColors = [
  { color: "blue", label: "SUPPORT" },
  { color: "red", label: "PICK" },
  { color: "pink", label: "PACK" },
  { color: "teal", label: "TEMPS MANQUANT" },
];

export const renderMinutes = (seconds) => {
  const rest = seconds % 60;
  const entier = Math.floor(seconds / 60);
  return entier + (rest > 0 ? 1 : 0);
};

export const activities = [
  {
    id: 1,
    activity: "Piking",
    productivity: "120",
    performance: "+8%",
    volumes: "199 000",
    objective: "100%",
    color: "#63A0F9",
  },
  {
    id: 2,
    activity: "Packing",
    productivity: "98",
    performance: "+2%",
    volumes: "199 000",
    objective: "99%",
    color: "#53E492",
  },
  {
    id: 3,
    activity: "Emballage",
    productivity: "110",
    performance: "-2%",
    volumes: "199 000",
    objective: "98%",
    color: "#8982DC",
  },
  {
    id: 4,
    activity: "Reception",
    productivity: "80",
    performance: "-2%",
    volumes: "199 000",
    objective: "90%",
    color: "#27817B",
  },
  {
    id: 5,
    activity: "Flashage",
    productivity: "120",
    performance: "+8%",
    volumes: "199 000",
    objective: "100%",
    color: "#f06bac",
  },
];

export const clients = [
  {
    id: 1,
    client: "BIC",
    productivity: "120",
    performance: "+8%",
    volumes: "199 000",
    objective: "100%",
    actId: 1,
  },
  {
    id: 2,
    client: "TIBET",
    productivity: "98",
    performance: "+2%",
    volumes: "199 000",
    objective: "99%",
    actId: 1,
  },
  {
    id: 3,
    client: "TIFED",
    productivity: "110",
    performance: "-2%",
    volumes: "199 000",
    objective: "98%",
    actId: 1,
  },
  {
    id: 4,
    client: "RENAULT",
    productivity: "80",
    performance: "-2%",
    volumes: "199 000",
    objective: "90%",
    actId: 1,
  },
  {
    id: 5,
    client: "PEUGEOT",
    productivity: "120",
    performance: "+8%",
    volumes: "199 000",
    objective: "100%",
    actId: 1,
  },
  {
    id: 6,
    client: "GLASSES",
    productivity: "98",
    performance: "+2%",
    volumes: "199 000",
    objective: "99%",
    actId: 1,
  },
  {
    id: 7,
    client: "LIGHT",
    productivity: "120",
    performance: "+8%",
    volumes: "199 000",
    objective: "100%",
    actId: 2,
  },
  {
    id: 8,
    client: "DREAM",
    productivity: "98",
    performance: "+2%",
    volumes: "199 000",
    objective: "99%",
    actId: 2,
  },
  {
    id: 9,
    client: "TIFED",
    productivity: "110",
    performance: "-2%",
    volumes: "199 000",
    objective: "98%",
    actId: 2,
  },
  {
    id: 10,
    client: "Jaguar",
    productivity: "80",
    performance: "-2%",
    volumes: "199 000",
    objective: "90%",
    actId: 3,
  },
  {
    id: 11,
    client: "PEUGEOT",
    productivity: "120",
    performance: "+8%",
    volumes: "199 000",
    objective: "100%",
    actId: 3,
  },
  {
    id: 12,
    client: "BOZAAR",
    productivity: "98",
    performance: "+2%",
    volumes: "199 000",
    objective: "99%",
    actId: 4,
  },

  {
    id: 13,
    client: "DREAM",
    productivity: "98",
    performance: "+2%",
    volumes: "199 000",
    objective: "99%",
    actId: 5,
  },
  {
    id: 14,
    client: "TIFED",
    productivity: "110",
    performance: "-2%",
    volumes: "199 000",
    objective: "98%",
    actId: 5,
  },
];

export const operators = [
  {
    id: 1,
    operator: "Jean Paul",
    productivity: "120",
    performance: "+8%",
    volumes: "199 000",
    objective: "100%",
    clientId: 1,
  },
  {
    id: 2,
    operator: "Mina Cloudia",
    productivity: "98",
    performance: "+2%",
    volumes: "199 000",
    objective: "99%",
    clientId: 1,
  },
  {
    id: 3,
    operator: "Arther Guidon",
    productivity: "110",
    performance: "-2%",
    volumes: "199 000",
    objective: "98%",
    clientId: 1,
  },
  {
    id: 4,
    operator: "Jupiter Ledon",
    productivity: "80",
    performance: "-2%",
    volumes: "199 000",
    objective: "90%",
    clientId: 1,
  },
  {
    id: 5,
    operator: "Rosaline trase",
    productivity: "120",
    performance: "+8%",
    volumes: "199 000",
    objective: "100%",
    clientId: 1,
  },
  {
    id: 6,
    operator: "Teressa boutwen",
    productivity: "98",
    performance: "+2%",
    volumes: "199 000",
    objective: "99%",
    clientId: 1,
  },
  {
    id: 7,
    operator: "Jean Paul",
    productivity: "120",
    performance: "+8%",
    volumes: "199 000",
    objective: "100%",
    clientId: 2,
  },
  {
    id: 8,
    operator: "Mina Cloudia",
    productivity: "98",
    performance: "+2%",
    volumes: "199 000",
    objective: "99%",
    clientId: 2,
  },
  {
    id: 9,
    operator: "Arther Guidon",
    productivity: "110",
    performance: "-2%",
    volumes: "199 000",
    objective: "98%",
    clientId: 2,
  },
  {
    id: 10,
    operator: "Jupiter Ledon",
    productivity: "80",
    performance: "-2%",
    volumes: "199 000",
    objective: "90%",
    clientId: 2,
  },
  {
    id: 11,
    operator: "Rosaline trase",
    productivity: "120",
    performance: "+8%",
    volumes: "199 000",
    objective: "100%",
    clientId: 2,
  },
  {
    id: 12,
    operator: "Teressa boutwen",
    productivity: "98",
    performance: "+2%",
    volumes: "199 000",
    objective: "99%",
    clientId: 2,
  },

  {
    id: 13,
    operator: "Jean Paul",
    productivity: "120",
    performance: "+8%",
    volumes: "199 000",
    objective: "100%",
    clientId: 3,
  },
  {
    id: 14,
    operator: "Mina Cloudia",
    productivity: "98",
    performance: "+2%",
    volumes: "199 000",
    objective: "99%",
    clientId: 3,
  },
  {
    id: 15,
    operator: "Arther Guidon",
    productivity: "110",
    performance: "-2%",
    volumes: "199 000",
    objective: "98%",
    clientId: 3,
  },
  {
    id: 16,
    operator: "Jupiter Ledon",
    productivity: "80",
    performance: "-2%",
    volumes: "199 000",
    objective: "90%",
    clientId: 4,
  },
  {
    id: 17,
    operator: "Rosaline trase",
    productivity: "120",
    performance: "+8%",
    volumes: "199 000",
    objective: "100%",
    clientId: 4,
  },
  {
    id: 17,
    operator: "Teressa boutwen",
    productivity: "98",
    performance: "+2%",
    volumes: "199 000",
    objective: "99%",
    clientId: 5,
  },

  {
    id: 18,
    operator: "Arther Guidon",
    productivity: "110",
    performance: "-2%",
    volumes: "199 000",
    objective: "98%",
    clientId: 3,
  },
  {
    id: 19,
    operator: "Jupiter Ledon",
    productivity: "80",
    performance: "-2%",
    volumes: "199 000",
    objective: "90%",
    clientId: 3,
  },
  {
    id: 20,
    operator: "Rosaline trase",
    productivity: "120",
    performance: "+8%",
    volumes: "199 000",
    objective: "100%",
    clientId: 3,
  },
  {
    id: 21,
    operator: "Teressa boutwen",
    productivity: "98",
    performance: "+2%",
    volumes: "199 000",
    objective: "99%",
    clientId: 3,
  },

  {
    id: 22,
    operator: "Mina Cloudia",
    productivity: "98",
    performance: "+2%",
    volumes: "199 000",
    objective: "99%",
    clientId: 6,
  },
  {
    id: 23,
    operator: "Arther Guidon",
    productivity: "110",
    performance: "-2%",
    volumes: "199 000",
    objective: "98%",
    clientId: 6,
  },
  {
    id: 24,
    operator: "Jupiter Ledon",
    productivity: "80",
    performance: "-2%",
    volumes: "199 000",
    objective: "90%",
    clientId: 6,
  },
  {
    id: 25,
    operator: "Rosaline trase",
    productivity: "120",
    performance: "+8%",
    volumes: "199 000",
    objective: "100%",
    clientId: 6,
  },

  {
    id: 26,
    operator: "Mina Cloudia",
    productivity: "98",
    performance: "+2%",
    volumes: "199 000",
    objective: "99%",
    clientId: 4,
  },
  {
    id: 27,
    operator: "Arther Guidon",
    productivity: "110",
    performance: "-2%",
    volumes: "199 000",
    objective: "98%",
    clientId: 4,
  },
  {
    id: 28,
    operator: "Jupiter Ledon",
    productivity: "80",
    performance: "-2%",
    volumes: "199 000",
    objective: "90%",
    clientId: 4,
  },
  {
    id: 29,
    operator: "Rosaline trase",
    productivity: "120",
    performance: "+8%",
    volumes: "199 000",
    objective: "100%",
    clientId: 4,
  },

  {
    id: 30,
    operator: "Mina Cloudia",
    productivity: "98",
    performance: "+2%",
    volumes: "199 000",
    objective: "99%",
    clientId: 10,
  },
  {
    id: 31,
    operator: "Arther Guidon",
    productivity: "110",
    performance: "-2%",
    volumes: "199 000",
    objective: "98%",
    clientId: 10,
  },

  {
    id: 32,
    operator: "Arther Guidon",
    productivity: "110",
    performance: "-2%",
    volumes: "199 000",
    objective: "98%",
    clientId: 11,
  },
  {
    id: 33,
    operator: "Jupiter Ledon",
    productivity: "80",
    performance: "-2%",
    volumes: "199 000",
    objective: "90%",
    clientId: 11,
  },

  {
    id: 34,
    operator: "Arther Guidon",
    productivity: "110",
    performance: "-2%",
    volumes: "199 000",
    objective: "98%",
    clientId: 12,
  },
  {
    id: 35,
    operator: "Jupiter Ledon",
    productivity: "80",
    performance: "-2%",
    volumes: "199 000",
    objective: "90%",
    clientId: 12,
  },

  {
    id: 36,
    operator: "Rosaline trase",
    productivity: "120",
    performance: "+8%",
    volumes: "199 000",
    objective: "100%",
    clientId: 13,
  },

  {
    id: 37,
    operator: "Mina Cloudia",
    productivity: "98",
    performance: "+2%",
    volumes: "199 000",
    objective: "99%",
    clientId: 13,
  },
  {
    id: 38,
    operator: "Arther Guidon",
    productivity: "110",
    performance: "-2%",
    volumes: "199 000",
    objective: "98%",
    clientId: 13,
  },

  {
    id: 39,
    operator: "Arther Guidon",
    productivity: "110",
    performance: "-2%",
    volumes: "199 000",
    objective: "98%",
    clientId: 7,
  },
  {
    id: 40,
    operator: "Jupiter Ledon",
    productivity: "80",
    performance: "-2%",
    volumes: "199 000",
    objective: "90%",
    clientId: 7,
  },

  {
    id: 41,
    operator: "Rosaline trase",
    productivity: "120",
    performance: "+8%",
    volumes: "199 000",
    objective: "100%",
    clientId: 8,
  },

  {
    id: 42,
    operator: "Mina Cloudia",
    productivity: "98",
    performance: "+2%",
    volumes: "199 000",
    objective: "99%",
    clientId: 8,
  },
  {
    id: 43,
    operator: "Arther Guidon",
    productivity: "110",
    performance: "-2%",
    volumes: "199 000",
    objective: "98%",
    clientId: 8,
  },

  {
    id: 44,
    operator: "Jupiter Ledon",
    productivity: "80",
    performance: "-2%",
    volumes: "199 000",
    objective: "90%",
    clientId: 9,
  },
  {
    id: 45,
    operator: "Rosaline trase",
    productivity: "120",
    performance: "+8%",
    volumes: "199 000",
    objective: "100%",
    clientId: 9,
  },

  {
    id: 46,
    operator: "Mina Cloudia",
    productivity: "98",
    performance: "+2%",
    volumes: "199 000",
    objective: "99%",
    clientId: 9,
  },
  {
    id: 47,
    operator: "Arther Guidon",
    productivity: "110",
    performance: "-2%",
    volumes: "199 000",
    objective: "98%",
    clientId: 9,
  },
  {
    id: 48,
    operator: "Rosaline trase",
    productivity: "120",
    performance: "+8%",
    volumes: "199 000",
    objective: "100%",
    clientId: 14,
  },
  {
    id: 49,
    operator: "Teressa boutwen",
    productivity: "98",
    performance: "+2%",
    volumes: "199 000",
    objective: "99%",
    clientId: 14,
  },

  {
    id: 50,
    operator: "Arther Guidon",
    productivity: "110",
    performance: "-2%",
    volumes: "199 000",
    objective: "98%",
    clientId: 14,
  },
  {
    id: 51,
    operator: "Jupiter Ledon",
    productivity: "80",
    performance: "-2%",
    volumes: "199 000",
    objective: "90%",
    clientId: 14,
  },
];

export const customOrder = (field, direction) => (a, b) => {
  if (direction === "asc") {
    if (a[field] < b[field]) {
      return -1;
    }
    if (a[field] > b[field]) {
      return 1;
    }
  } else {
    if (a[field] > b[field]) {
      return -1;
    }
    if (a[field] < b[field]) {
      return 1;
    }
  }
  return 0;
};
